version: "2"
services:
    gateway:
      image: hsweb/hsweb-examples-cloud-gateway:3.0-SNAPSHOT
      ports:
        - 8761:8761
      hostname: gateway
    user-center:
      image: hsweb/hsweb-examples-cloud-user-center:3.0-SNAPSHOT
      links:
          - gateway:gateway
      hostname: user-center
    service01:
      image: hsweb/hsweb-examples-cloud-service01:3.0-SNAPSHOT
      links:
          - gateway:gateway
      hostname: service01