on:
  port: 8080
  address: 0.0.0.0

admin:
  port: ${on.port}
  address: ${on.address}

app:
  contextPath: ''
  home: /

gui:
  search: false
  navbar: true
  fluid: false
  cdn: auto
  menu: {}

main-zone: {}

users:
  admin:
    roles: administrator

jobs:
  executor:
    threads: 256
  scheduler:
    threads: 64

jdbc:
  host: localhost
  driver: UNKNOWN
  username: UNKNOWN
  password: UNKNOWN
  url: UNKNOWN
  options: ''
  poolProvider: hikari

hibernate:
  dialect: UNKNOWN

c3p0:
  debug: false
  initialPoolSize: 5
  minPoolSize: 5
  maxPoolSize: 100
  acquireIncrement: 5
  maxStatementsPerConnection: 10
  idleConnectionTestPeriod: 300

hikari: {}

oauth:
  google:
    scope: profile,email
    clientId: YOUR_GOOGLE_CLIENT_ID_HERE
    clientSecret: YOUR_GOOGLE_CLIENT_SECRET_HERE

  github:
    scope: user:email
    clientId: YOUR_GITHUB_CLIENT_ID_HERE
    clientSecret: YOUR_GITHUB_CLIENT_SECRET_HERE

  facebook:
    scope: public_profile,email
    clientId: YOUR_FACEBOOK_CLIENT_ID_HERE
    clientSecret: YOUR_FACEBOOK_CLIENT_SECRET_HERE

  linkedin:
    scope: r_basicprofile,r_emailaddress
    clientId: YOUR_LINKEDIN_CLIENT_ID_HERE
    clientSecret: YOUR_LINKEDIN_CLIENT_SECRET_HERE

net:
  address: 0.0.0.0
  port: 8080
#  workers: ${system.cpus}
  bufSizeKB: 256
  noDelay: false
  syncBufs: true
  blockingAccept: false

http:
  timeout: 30000
  timeoutResolution: 5000
  maxPipeline: 10
  serverName: Rapidoid

  mandatoryHeaders:
    connection: true
    date: true
    server: true
    contentType: true

reverse-proxy:
  timeout: 10000
  retryDelay: 300
  maxConnections: 100
  maxConnectionsPerRoute: 100
  reuseConnections: true
  setHeaders:
    X-Forwarded-For: true
    X-Client-IP: false
    X-Real-IP: false
    X-Username: false
    X-Roles: false

token:
  ttl: 0 # unlimited

log:
  level: info
  fancy: false # auto

tls:
  selfSigned: true
  enabled: false
  keystore: ''
  keystorePassword: ''
  keyManagerPassword: ''
  truststore: ''
  truststorePassword: ''
