jdbc:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://${jdbc.host}:${jdbc.port}/?${jdbc.options}
  username: postgres
  password: postgres
  port: 5432
  options: loglevel=1

hibernate:
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
