#dist: trusty
sudo: false
language: java
services: docker
addons:
  hosts:
    - mariadb.example.com

before_install:
    - chmod +x .travis/script.sh
    - echo "MAVEN_OPTS='-Xmx384m'" > ~/.mavenrc
install:

    # generate SSL certificates
    - mkdir tmp
    - .travis/gen-ssl.sh mariadb.example.com tmp
    - export PROJ_PATH=`pwd`
    - export SSLCERT=$PROJ_PATH/tmp
    - export ENTRYPOINT=$PROJ_PATH/.travis/sql

cache:
  directories:
    - $HOME/.m2

jdk:
    - oraclejdk8
    - oraclejdk9

env:
    - AURORA=true
    - DB=mysql:5.5 PACKET=8M
    - DB=mysql:5.6 PACKET=8M
    - DB=mysql:5.7 PACKET=8M
    - DB=mariadb:5.5 PACKET=8M
    - DB=mariadb:10.0 PACKET=8M
    - DB=mariadb:10.1 PACKET=8M
    - DB=mariadb:10.2 PACKET=8M
    - DB=mariadb:10.2 PACKET=8M GALERA=true
    - DB=mariadb:10.2 PACKET=8M PROFILE=true
    - DB=mariadb:10.2 PACKET=8M TYPE=PREPARE
    - DB=mariadb:10.2 PACKET=8M TYPE=REWRITE
    - DB=mariadb:10.2 PACKET=8M TYPE=MULTI
    - DB=mariadb:10.2 PACKET=20M
    - DB=mariadb:10.2 PACKET=40M
    - DB=mariadb:10.2 PACKET=40M TYPE=BULK_SERVER
    - DB=mariadb:10.2 PACKET=40M TYPE=NO_BULK_CLIENT
    - DB=mariadb:10.2 PACKET=40M TYPE=NO_BULK_SERVER
    - DB=mariadb:10.2 PACKET=40M COMPRESSION=true
    - DB=mariadb:10.3 PACKET=8M
    - DB=mariadb:10.2 PACKET=8M MAXSCALE_VERSION=2.1.8
script: .travis/script.sh
