language: java

jdk:
 - openjdk8
 
sudo: required

before_install:
  - cat /etc/hosts # optionally check the content *before*
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
  - cat /etc/hosts # optionally check the content *after*

#solved in pom.xml
#env: MAVEN_OPTS="-Dio.netty.leakDetectionLevel=paranoid"

#does not work as reported here: https://github.com/travis-ci/travis-ci/issues/1341
#before_script: 
# - chmod a+x /home/travis/build/tomp2p/TomP2P/nat/src/test/resources/nat-net.sh
# - sudo sh -c 'echo "travis ALL=(ALL) NOPASSWD":" /home/travis/build/tomp2p/TomP2P/nat/src/test/resources/nat-net.sh" >> /etc/sudoers'
# - sudo sh -c 'echo "travis ALL=(ALL) NOPASSWD":" /usr/bin/ip" >> /etc/sudoers'


