language: java
before_install:
  - wget https://releases.hashicorp.com/consul/0.7.2/consul_0.7.2_linux_amd64.zip --no-check-certificate
  - unzip consul_0.7.2_linux_amd64.zip
  - ./consul agent -server -bootstrap -data-dir data &
jdk:
  - oraclejdk7
script: mvn clean test

