install:
 - mvn clean
script:
 - mvn -B -fae -Dserver.version=$SERVER_VERSION install

language: java
jdk:
  - oraclejdk8
  - oraclejdk9
env:
  - SERVER_VERSION=10.1.0.Final
  - SERVER_VERSION=10.0.0.Final
  - SERVER_VERSION=11.0.0.CR1
cache:
 directories:
  - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - "if [ -d \"$JAVA_HOME/jre\" ]; then SEC_LIB=$JAVA_HOME/jre; else SEC_LIB=$JAVA_HOME; fi; sudo unzip -j -o  travis-libs/jce_policy-8.zip *.jar -d $SEC_LIB/lib/security;"
