language: java
jdk: oraclejdk8
addons:
  sonarqube:
    token:
      secure: "a688e735dd959a7bda8303306bcedec5ec463cee"
branches:
  only:
    - master
    - 3.0.0-SNAPSHOT
script: 
    - mvn clean install -Pjacoco -Pcoveralls coveralls:report sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/112bda97234dac298c06
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  slack:
    on_success: always
    on_failure: always 
  email:
    recipients:
      - demoiselle-devel@lists.sourceforge.net
    on_success: change
    on_failure: always
