language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "hsweb"
    token:
      secure: "fba01e9fb57104fd0cfbed380e8c90301e35ff09"
jdk:
  - oraclejdk8
script:
  - mvn clean jacoco:report package -Dmaven.test.failure.ignore=true sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'