language: java
sudo: false

before_install:
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
   - echo $JAVA_HOME
   
matrix:
  include:
    # this is the current Travis default JDK on linux
    # - os: linux
    #   jdk: oraclejdk7
    - os: linux
      jdk: oraclejdk8
    # - os: linux
    #  jdk: openjdk8
    - os: linux
      jdk: openjdk7
    - os: linux
      jdk: openjdk6
    # this is the current Travis default JDK on osx
    # - os: osx
    #   env: JAVA_HOME=/usr/libexec/java_home

os:
  - linux
  - osx

notifications:
  irc:
    channels:
      - "irc.freenode.org#jnr"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
