
spring:
    aop:
        auto: true
        proxy-target-class: true
    datasource:
       url : jdbc:h2:mem:example-oauth2-client
       username : sa
       password :
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name : org.h2.Driver
    cache:
       type: simple
hsweb:
    app:
      name: hsweb-oauth2 客户端示例
      version: 3.0.0
server:
  port: 8808