gui:
  title: Books
  brand: Books
  search: false
  fluid: false
  menu:
    Home: /
    Overview: /overview
    API (right):
      Books: /books
    Help:
      About: /about

api:
  /books: sql/books.sql

pages:
  /: sql/books.sql

  /overview:
    gui:
      all_books:
        pageSize: 3
        caption: 'List of books:'
        header: Books
        footer: The footer
        sql: sql/books.sql

  /about: ''
