spring:
  aop:
      auto: true
  datasource:
     url : jdbc:h2:mem:permission_test_mem
     username : sa
     password :
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name : org.h2.Driver
hsweb:
    app:
      name: 权限管理测试
      version: 3.0.0
    cloud:
      user-center:
        name: gateway
        prefix: /api/user-center/
server:
    port: 9001
logging:
  level:
    org.hswebframework.web: debug
